-- Pre-cleaning summary for one LOAD_RUN_ID; read-only.
-- Duplicate rows exclude ingestion metadata. Missing IDs mean NULL or empty text,
-- matching Northstar; whitespace-only IDs are not counted as missing here.
WITH CURRENT_LOAD AS (
    SELECT *
    FROM CLEANSTAR.RAW.BILLING_CLAIMS_RAW
    WHERE LOAD_RUN_ID = %s
),
CLAIM_AMOUNT_AS_NUMERIC AS (
    SELECT *,
           TRY_TO_NUMBER(CLAIM_AMOUNT, 38, 2) AS CLAIM_AMOUNT_NUMERIC
    FROM CURRENT_LOAD
)
SELECT
    COUNT(*) AS row_count,
    (SELECT COALESCE(SUM(occurrence - 1), 0) AS duplicate_count
            FROM (SELECT COUNT(*) AS occurrence
                    FROM CURRENT_LOAD
                    GROUP BY CLAIM_ID, ENCOUNTER_ID, PATIENT_ID, PROVIDER_ID, ORGANIZATION_ID, PAYER_ID, 
                            INSURANCE_PLAN_NAME, MEMBER_ID, GROUP_NUMBER, RELATIONSHIP_TO_INSURED, PATIENT_FIRST_NAME, 
                            PATIENT_MIDDLE_INITIAL, PATIENT_LAST_NAME, PATIENT_SUFFIX, PATIENT_BIRTHDATE, PATIENT_GENDER, 
                            PATIENT_ADDRESS, PATIENT_CITY, PATIENT_STATE, PATIENT_ZIP, PATIENT_PHONE, SERVICE_START_DATETIME,
                            SERVICE_END_DATETIME, ENCOUNTER_CLASS, PROCEDURE_CODE, PROCEDURE_DESCRIPTION,
                            DIAGNOSIS_CODE, DIAGNOSIS_DESCRIPTION, CLAIM_AMOUNT, PROVIDER_NAME, PROVIDER_NPI, 
                            PROVIDER_SPECIALTY, CLAIM_STATUS, CLAIM_CREATED_DATETIME, VALIDATION_ERROR_COUNT, VALIDATION_ERRORS
                    HAVING COUNT(*) > 1) AS duplicate_rows) AS duplicate_rows,
    COUNT(TRIM(CLAIM_ID)) - COUNT(DISTINCT TRIM(CLAIM_ID)) AS duplicate_claim_ids,
    COALESCE(SUM(CASE WHEN CLAIM_ID IS NULL OR CLAIM_ID = '' THEN 1 ELSE 0 END), 0) AS missing_claim_ids,
    COALESCE(SUM(CASE WHEN PATIENT_ID IS NULL OR PATIENT_ID = '' THEN 1 ELSE 0 END), 0) AS missing_patient_ids,
    COALESCE(SUM(CASE WHEN ENCOUNTER_ID IS NULL OR ENCOUNTER_ID = '' THEN 1 ELSE 0 END), 0) AS missing_encounter_ids,
    COALESCE(SUM(CASE WHEN CLAIM_AMOUNT_NUMERIC < 0 THEN 1 ELSE 0 END), 0) AS negative_claim_amounts
FROM CLAIM_AMOUNT_AS_NUMERIC;
