-- Learning example: first 10 billing-claims data records (header is skipped).
-- Requires the file to have been uploaded and the table/file format to exist.
-- Fixed sample metadata, not a real pipeline run.
-- INSERT does not use COPY load history: rerunning inserts these rows again.
INSERT INTO CLEANSTAR.RAW.BILLING_CLAIMS_RAW (
    "CLAIM_ID",
    "ENCOUNTER_ID",
    "PATIENT_ID",
    "PROVIDER_ID",
    "ORGANIZATION_ID",
    "PAYER_ID",
    "INSURANCE_PLAN_NAME",
    "MEMBER_ID",
    "GROUP_NUMBER",
    "RELATIONSHIP_TO_INSURED",
    "PATIENT_FIRST_NAME",
    "PATIENT_MIDDLE_INITIAL",
    "PATIENT_LAST_NAME",
    "PATIENT_SUFFIX",
    "PATIENT_BIRTHDATE",
    "PATIENT_GENDER",
    "PATIENT_ADDRESS",
    "PATIENT_CITY",
    "PATIENT_STATE",
    "PATIENT_ZIP",
    "PATIENT_PHONE",
    "SERVICE_START_DATETIME",
    "SERVICE_END_DATETIME",
    "ENCOUNTER_CLASS",
    "PROCEDURE_CODE",
    "PROCEDURE_DESCRIPTION",
    "DIAGNOSIS_CODE",
    "DIAGNOSIS_DESCRIPTION",
    "CLAIM_AMOUNT",
    "PROVIDER_NAME",
    "PROVIDER_NPI",
    "PROVIDER_SPECIALTY",
    "CLAIM_STATUS",
    "CLAIM_CREATED_DATETIME",
    "VALIDATION_ERROR_COUNT",
    "VALIDATION_ERRORS",
    LOAD_RUN_ID,
    SOURCE_FILE,
    INGESTED_AT
)
SELECT
    staged_file.$1 AS "CLAIM_ID",
    staged_file.$2 AS "ENCOUNTER_ID",
    staged_file.$3 AS "PATIENT_ID",
    staged_file.$4 AS "PROVIDER_ID",
    staged_file.$5 AS "ORGANIZATION_ID",
    staged_file.$6 AS "PAYER_ID",
    staged_file.$7 AS "INSURANCE_PLAN_NAME",
    staged_file.$8 AS "MEMBER_ID",
    staged_file.$9 AS "GROUP_NUMBER",
    staged_file.$10 AS "RELATIONSHIP_TO_INSURED",
    staged_file.$11 AS "PATIENT_FIRST_NAME",
    staged_file.$12 AS "PATIENT_MIDDLE_INITIAL",
    staged_file.$13 AS "PATIENT_LAST_NAME",
    staged_file.$14 AS "PATIENT_SUFFIX",
    staged_file.$15 AS "PATIENT_BIRTHDATE",
    staged_file.$16 AS "PATIENT_GENDER",
    staged_file.$17 AS "PATIENT_ADDRESS",
    staged_file.$18 AS "PATIENT_CITY",
    staged_file.$19 AS "PATIENT_STATE",
    staged_file.$20 AS "PATIENT_ZIP",
    staged_file.$21 AS "PATIENT_PHONE",
    staged_file.$22 AS "SERVICE_START_DATETIME",
    staged_file.$23 AS "SERVICE_END_DATETIME",
    staged_file.$24 AS "ENCOUNTER_CLASS",
    staged_file.$25 AS "PROCEDURE_CODE",
    staged_file.$26 AS "PROCEDURE_DESCRIPTION",
    staged_file.$27 AS "DIAGNOSIS_CODE",
    staged_file.$28 AS "DIAGNOSIS_DESCRIPTION",
    staged_file.$29 AS "CLAIM_AMOUNT",
    staged_file.$30 AS "PROVIDER_NAME",
    staged_file.$31 AS "PROVIDER_NPI",
    staged_file.$32 AS "PROVIDER_SPECIALTY",
    staged_file.$33 AS "CLAIM_STATUS",
    staged_file.$34 AS "CLAIM_CREATED_DATETIME",
    staged_file.$35 AS "VALIDATION_ERROR_COUNT",
    staged_file.$36 AS "VALIDATION_ERRORS",
    'example-first-10-20260924' AS LOAD_RUN_ID,
    'billing_claims_dirty.csv' AS SOURCE_FILE,
    '2026-09-24T12:00:00+00:00'::TIMESTAMP_TZ AS INGESTED_AT
FROM @CLEANSTAR.RAW.RAW_STAGE/billing_claims_dirty.csv.gz
    (FILE_FORMAT => 'CLEANSTAR.RAW.CSV_FORMAT') staged_file
WHERE METADATA$FILENAME = 'billing_claims_dirty.csv.gz'
ORDER BY METADATA$FILE_ROW_NUMBER
LIMIT 10;
