-- Fully expanded loader example for billing claims. Loads the WHOLE file.
-- Fixed sample metadata; do not confuse this with the 10-row example.
COPY INTO IDENTIFIER('CLEANSTAR.RAW.BILLING_CLAIMS_RAW') (
    "CLAIM_ID",
    "ENCOUNTER_ID",
    "PATIENT_ID",
    "PROVIDER_ID",
    "ORGANIZATION_ID",
    "PAYER_ID",
    "INSURANCE_PLAN_NAME",
    "MEMBER_ID",
    "GROUP_NUMBER",
    "RELATIONSHIP_TO_INSURED",
    "PATIENT_FIRST_NAME",
    "PATIENT_MIDDLE_INITIAL",
    "PATIENT_LAST_NAME",
    "PATIENT_SUFFIX",
    "PATIENT_BIRTHDATE",
    "PATIENT_GENDER",
    "PATIENT_ADDRESS",
    "PATIENT_CITY",
    "PATIENT_STATE",
    "PATIENT_ZIP",
    "PATIENT_PHONE",
    "SERVICE_START_DATETIME",
    "SERVICE_END_DATETIME",
    "ENCOUNTER_CLASS",
    "PROCEDURE_CODE",
    "PROCEDURE_DESCRIPTION",
    "DIAGNOSIS_CODE",
    "DIAGNOSIS_DESCRIPTION",
    "CLAIM_AMOUNT",
    "PROVIDER_NAME",
    "PROVIDER_NPI",
    "PROVIDER_SPECIALTY",
    "CLAIM_STATUS",
    "CLAIM_CREATED_DATETIME",
    "VALIDATION_ERROR_COUNT",
    "VALIDATION_ERRORS",
    LOAD_RUN_ID, SOURCE_FILE, INGESTED_AT
)
FROM (
    SELECT
        staged_file.$1,
        staged_file.$2,
        staged_file.$3,
        staged_file.$4,
        staged_file.$5,
        staged_file.$6,
        staged_file.$7,
        staged_file.$8,
        staged_file.$9,
        staged_file.$10,
        staged_file.$11,
        staged_file.$12,
        staged_file.$13,
        staged_file.$14,
        staged_file.$15,
        staged_file.$16,
        staged_file.$17,
        staged_file.$18,
        staged_file.$19,
        staged_file.$20,
        staged_file.$21,
        staged_file.$22,
        staged_file.$23,
        staged_file.$24,
        staged_file.$25,
        staged_file.$26,
        staged_file.$27,
        staged_file.$28,
        staged_file.$29,
        staged_file.$30,
        staged_file.$31,
        staged_file.$32,
        staged_file.$33,
        staged_file.$34,
        staged_file.$35,
        staged_file.$36,
        'example-first-10-20260924',
        'billing_claims_dirty.csv',
        '2026-09-24T12:00:00+00:00'::TIMESTAMP_TZ
    FROM @CLEANSTAR.RAW.RAW_STAGE staged_file
)
FILES = ('billing_claims_dirty.csv.gz')
FILE_FORMAT = (FORMAT_NAME = 'CLEANSTAR.RAW.CSV_FORMAT')
ON_ERROR = ABORT_STATEMENT
FORCE = FALSE
PURGE = FALSE;
