-- Generated from src/cleanstar/data_config.py; regenerate when definitions change.
-- Run after schemas.sql with CREATE TABLE privileges in the target schema.
-- IF NOT EXISTS preserves existing tables; it does not update their definitions.
-- Source columns remain VARCHAR; metadata uses the configured data types.

CREATE TABLE IF NOT EXISTS CLEANSTAR.RAW.BILLING_CLAIMS_RAW (
    CLAIM_ID VARCHAR,
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    PROVIDER_ID VARCHAR,
    ORGANIZATION_ID VARCHAR,
    PAYER_ID VARCHAR,
    INSURANCE_PLAN_NAME VARCHAR,
    MEMBER_ID VARCHAR,
    GROUP_NUMBER VARCHAR,
    RELATIONSHIP_TO_INSURED VARCHAR,
    PATIENT_FIRST_NAME VARCHAR,
    PATIENT_MIDDLE_INITIAL VARCHAR,
    PATIENT_LAST_NAME VARCHAR,
    PATIENT_SUFFIX VARCHAR,
    PATIENT_BIRTHDATE VARCHAR,
    PATIENT_GENDER VARCHAR,
    PATIENT_ADDRESS VARCHAR,
    PATIENT_CITY VARCHAR,
    PATIENT_STATE VARCHAR,
    PATIENT_ZIP VARCHAR,
    PATIENT_PHONE VARCHAR,
    SERVICE_START_DATETIME VARCHAR,
    SERVICE_END_DATETIME VARCHAR,
    ENCOUNTER_CLASS VARCHAR,
    PROCEDURE_CODE VARCHAR,
    PROCEDURE_DESCRIPTION VARCHAR,
    DIAGNOSIS_CODE VARCHAR,
    DIAGNOSIS_DESCRIPTION VARCHAR,
    CLAIM_AMOUNT VARCHAR,
    PROVIDER_NAME VARCHAR,
    PROVIDER_NPI VARCHAR,
    PROVIDER_SPECIALTY VARCHAR,
    CLAIM_STATUS VARCHAR,
    CLAIM_CREATED_DATETIME VARCHAR,
    VALIDATION_ERROR_COUNT VARCHAR,
    VALIDATION_ERRORS VARCHAR,
    LOAD_RUN_ID VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CLEANSTAR.RAW.ENCOUNTER_INFO_RAW (
    ENCOUNTER_ID VARCHAR,
    START_DATETIME VARCHAR,
    END_DATETIME VARCHAR,
    PATIENT_ID VARCHAR,
    ORGANIZATION_ID VARCHAR,
    PROVIDER_ID VARCHAR,
    ENCOUNTER_CLASS VARCHAR,
    ENCOUNTER_CODE VARCHAR,
    ENCOUNTER_DESCRIPTION VARCHAR,
    DIAGNOSIS_CODE VARCHAR,
    DIAGNOSIS_DESCRIPTION VARCHAR,
    BASE_ENCOUNTER_COST VARCHAR,
    LOAD_RUN_ID VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CLEANSTAR.RAW.PATIENT_INFO_RAW (
    PATIENT_ID VARCHAR,
    BIRTHDATE VARCHAR,
    FIRST_NAME VARCHAR,
    MIDDLE_INITIAL VARCHAR,
    LAST_NAME VARCHAR,
    SUFFIX VARCHAR,
    GENDER VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP VARCHAR,
    PHONE VARCHAR,
    PAYER_ID VARCHAR,
    INSURANCE_PLAN_NAME VARCHAR,
    MEMBER_ID VARCHAR,
    GROUP_NUMBER VARCHAR,
    RELATIONSHIP_TO_INSURED VARCHAR,
    COVERAGE_START_DATE VARCHAR,
    COVERAGE_END_DATE VARCHAR,
    COVERAGE_STATUS VARCHAR,
    LOAD_RUN_ID VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS CLEANSTAR.RAW.PROVIDER_INFO_RAW (
    PROVIDER_ID VARCHAR,
    ORGANIZATION_ID VARCHAR,
    PROVIDER_NAME VARCHAR,
    SPECIALTY VARCHAR,
    NPI VARCHAR,
    LOAD_RUN_ID VARCHAR,
    SOURCE_FILE VARCHAR,
    INGESTED_AT TIMESTAMP_TZ
);
