-- Categorize prepared patient records; retain raw values and quality reasons.
-- Parameter: LOAD_RUN_ID. Use the same session as prepare_patient.sql.
-- Priority: QUARANTINED, DEDUPLICATED, WARNING, CLEAN.
-- Original source hashes detect duplicates; normalized IDs detect conflicts.
CREATE TEMPORARY TABLE CLEANSTAR.RAW.CATEGORIZED_PATIENT AS
WITH CURRENT_LOAD AS (
    SELECT * FROM CLEANSTAR.RAW.PREPARED_PATIENT
    WHERE LOAD_RUN_ID = %s
),
RANKED_ROWS AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY SOURCE_ROW_HASH
            ORDER BY INGESTED_AT, SOURCE_FILE, PATIENT_ID
        ) AS DUPLICATE_NUMBER
    FROM CURRENT_LOAD
),
CURRENT_CONFLICTS AS (
    SELECT PATIENT_ID
    FROM CURRENT_LOAD
    WHERE PATIENT_ID IS NOT NULL
    GROUP BY PATIENT_ID
    HAVING COUNT(DISTINCT SOURCE_ROW_HASH) > 1
),
HISTORICAL_DUPLICATES AS (
    SELECT DISTINCT source.SOURCE_ROW_HASH
    FROM CURRENT_LOAD AS source
    WHERE EXISTS (
        SELECT 1 FROM CLEANSTAR.CLEAN.PATIENT_INFO_CLEAN AS clean
        WHERE clean.SOURCE_ROW_HASH = source.SOURCE_ROW_HASH
          AND clean.LOAD_RUN_ID <> source.LOAD_RUN_ID
    )
),
HISTORICAL_CONFLICTS AS (
    SELECT DISTINCT source.PATIENT_ID, source.SOURCE_ROW_HASH
    FROM CURRENT_LOAD AS source
    WHERE EXISTS (
        SELECT 1 FROM CLEANSTAR.CLEAN.PATIENT_INFO_CLEAN AS clean
        WHERE clean.PATIENT_ID = source.PATIENT_ID
          AND clean.SOURCE_ROW_HASH <> source.SOURCE_ROW_HASH
          AND clean.LOAD_RUN_ID <> source.LOAD_RUN_ID
    )
),
HISTORY_FLAGS AS (
    SELECT source.*,
        (conflict.PATIENT_ID IS NOT NULL) AS CURRENT_CONFLICT,
        (duplicate.SOURCE_ROW_HASH IS NOT NULL) AS HISTORICAL_DUPLICATE,
        (history.PATIENT_ID IS NOT NULL) AS HISTORICAL_CONFLICT
    FROM RANKED_ROWS AS source
    LEFT JOIN CURRENT_CONFLICTS AS conflict ON source.PATIENT_ID = conflict.PATIENT_ID
    LEFT JOIN HISTORICAL_DUPLICATES AS duplicate
        ON source.SOURCE_ROW_HASH = duplicate.SOURCE_ROW_HASH
    LEFT JOIN HISTORICAL_CONFLICTS AS history
        ON source.PATIENT_ID = history.PATIENT_ID
       AND source.SOURCE_ROW_HASH = history.SOURCE_ROW_HASH
),
RULE_FLAGS AS (
    SELECT *,
        IFF(DUPLICATE_NUMBER > 1, TRUE, FALSE) AS RULE_PAT_001,
        IFF(CURRENT_CONFLICT, TRUE, FALSE) AS RULE_PAT_002,
        IFF(PATIENT_ID IS NULL, TRUE, FALSE) AS RULE_PAT_003,
        IFF(BIRTHDATE_CONVERSION_FAILED, TRUE, FALSE) AS RULE_PAT_004,
        IFF(ZIP IS NOT NULL AND NOT REGEXP_LIKE(ZIP, '^[0-9]{5}(-[0-9]{4})?$'), TRUE, FALSE) AS RULE_PAT_005,
        IFF(HISTORICAL_DUPLICATE, TRUE, FALSE) AS RULE_PAT_006,
        IFF(HISTORICAL_CONFLICT, TRUE, FALSE) AS RULE_PAT_007,
        IFF(COVERAGE_START_DATE_CONVERSION_FAILED, TRUE, FALSE) AS RULE_PAT_008,
        IFF(COVERAGE_END_DATE_CONVERSION_FAILED, TRUE, FALSE) AS RULE_PAT_009
    FROM HISTORY_FLAGS
)
SELECT *,
    CASE
        WHEN RULE_PAT_002 OR RULE_PAT_003 OR RULE_PAT_004 OR RULE_PAT_007 OR RULE_PAT_008 OR RULE_PAT_009 THEN 'QUARANTINED'
        WHEN RULE_PAT_001 OR RULE_PAT_006 THEN 'DEDUPLICATED'
        WHEN RULE_PAT_005 THEN 'WARNING'
        ELSE 'CLEAN'
    END AS VALIDATION_STATUS,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(RULE_PAT_001, 'PAT-001', NULL),
        IFF(RULE_PAT_002, 'PAT-002', NULL),
        IFF(RULE_PAT_003, 'PAT-003', NULL),
        IFF(RULE_PAT_004, 'PAT-004', NULL),
        IFF(RULE_PAT_005, 'PAT-005', NULL),
        IFF(RULE_PAT_006, 'PAT-006', NULL),
        IFF(RULE_PAT_007, 'PAT-007', NULL),
        IFF(RULE_PAT_008, 'PAT-008', NULL),
        IFF(RULE_PAT_009, 'PAT-009', NULL)
    ), ', '), '') AS VALIDATION_RULE_IDS,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(RULE_PAT_001, 'Exact duplicate row within current load', NULL),
        IFF(RULE_PAT_002, 'ID is reused by conflicting records within current load', NULL),
        IFF(RULE_PAT_003, 'Patient ID is required', NULL),
        IFF(RULE_PAT_004, 'Birthdate must be a valid date', NULL),
        IFF(RULE_PAT_005, 'ZIP must contain 5 digits or ZIP+4', NULL),
        IFF(RULE_PAT_006, 'Exact record already exists in CLEAN from an earlier load', NULL),
        IFF(RULE_PAT_007, 'ID conflicts with a CLEAN record from an earlier load', NULL),
        IFF(RULE_PAT_008, 'Coverage start must be a valid date', NULL),
        IFF(RULE_PAT_009, 'Coverage end must be a valid date', NULL)
    ), '; '), '') AS VALIDATION_MESSAGES
FROM RULE_FLAGS;
