-- Categorize prepared encounter records; retain raw values and quality reasons.
-- Parameter: LOAD_RUN_ID. Use the same session as prepare_encounter.sql.
-- Priority: QUARANTINED, DEDUPLICATED, WARNING, CLEAN.
-- Original source hashes detect duplicates; normalized IDs detect conflicts.
CREATE TEMPORARY TABLE CLEANSTAR.RAW.CATEGORIZED_ENCOUNTER AS
WITH CURRENT_LOAD AS (
    SELECT * FROM CLEANSTAR.RAW.PREPARED_ENCOUNTER
    WHERE LOAD_RUN_ID = %s
),
RANKED_ROWS AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY SOURCE_ROW_HASH
            ORDER BY INGESTED_AT, SOURCE_FILE, ENCOUNTER_ID
        ) AS DUPLICATE_NUMBER
    FROM CURRENT_LOAD
),
CURRENT_CONFLICTS AS (
    SELECT ENCOUNTER_ID
    FROM CURRENT_LOAD
    WHERE ENCOUNTER_ID IS NOT NULL
    GROUP BY ENCOUNTER_ID
    HAVING COUNT(DISTINCT SOURCE_ROW_HASH) > 1
),
HISTORICAL_DUPLICATES AS (
    SELECT DISTINCT source.SOURCE_ROW_HASH
    FROM CURRENT_LOAD AS source
    WHERE EXISTS (
        SELECT 1 FROM CLEANSTAR.CLEAN.ENCOUNTER_INFO_CLEAN AS clean
        WHERE clean.SOURCE_ROW_HASH = source.SOURCE_ROW_HASH
          AND clean.LOAD_RUN_ID <> source.LOAD_RUN_ID
    )
),
HISTORICAL_CONFLICTS AS (
    SELECT DISTINCT source.ENCOUNTER_ID, source.SOURCE_ROW_HASH
    FROM CURRENT_LOAD AS source
    WHERE EXISTS (
        SELECT 1 FROM CLEANSTAR.CLEAN.ENCOUNTER_INFO_CLEAN AS clean
        WHERE clean.ENCOUNTER_ID = source.ENCOUNTER_ID
          AND clean.SOURCE_ROW_HASH <> source.SOURCE_ROW_HASH
          AND clean.LOAD_RUN_ID <> source.LOAD_RUN_ID
    )
),
HISTORY_FLAGS AS (
    SELECT source.*,
        (conflict.ENCOUNTER_ID IS NOT NULL) AS CURRENT_CONFLICT,
        (duplicate.SOURCE_ROW_HASH IS NOT NULL) AS HISTORICAL_DUPLICATE,
        (history.ENCOUNTER_ID IS NOT NULL) AS HISTORICAL_CONFLICT
    FROM RANKED_ROWS AS source
    LEFT JOIN CURRENT_CONFLICTS AS conflict ON source.ENCOUNTER_ID = conflict.ENCOUNTER_ID
    LEFT JOIN HISTORICAL_DUPLICATES AS duplicate
        ON source.SOURCE_ROW_HASH = duplicate.SOURCE_ROW_HASH
    LEFT JOIN HISTORICAL_CONFLICTS AS history
        ON source.ENCOUNTER_ID = history.ENCOUNTER_ID
       AND source.SOURCE_ROW_HASH = history.SOURCE_ROW_HASH
),
RULE_FLAGS AS (
    SELECT *,
        IFF(DUPLICATE_NUMBER > 1, TRUE, FALSE) AS RULE_ENC_001,
        IFF(CURRENT_CONFLICT, TRUE, FALSE) AS RULE_ENC_002,
        IFF(ENCOUNTER_ID IS NULL, TRUE, FALSE) AS RULE_ENC_003,
        IFF(PATIENT_ID IS NULL, TRUE, FALSE) AS RULE_ENC_004,
        IFF(PROVIDER_ID IS NULL, TRUE, FALSE) AS RULE_ENC_005,
        IFF(HISTORICAL_DUPLICATE, TRUE, FALSE) AS RULE_ENC_006,
        IFF(HISTORICAL_CONFLICT, TRUE, FALSE) AS RULE_ENC_007,
        IFF(START_DATETIME_CONVERSION_FAILED, TRUE, FALSE) AS RULE_ENC_008,
        IFF(END_DATETIME_CONVERSION_FAILED, TRUE, FALSE) AS RULE_ENC_009,
        IFF(BASE_ENCOUNTER_COST_CONVERSION_FAILED, TRUE, FALSE) AS RULE_ENC_010
    FROM HISTORY_FLAGS
)
SELECT *,
    CASE
        WHEN RULE_ENC_002 OR RULE_ENC_003 OR RULE_ENC_004 OR RULE_ENC_005 OR RULE_ENC_007 OR RULE_ENC_008 OR RULE_ENC_009 OR RULE_ENC_010 THEN 'QUARANTINED'
        WHEN RULE_ENC_001 OR RULE_ENC_006 THEN 'DEDUPLICATED'
        ELSE 'CLEAN'
    END AS VALIDATION_STATUS,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(RULE_ENC_001, 'ENC-001', NULL),
        IFF(RULE_ENC_002, 'ENC-002', NULL),
        IFF(RULE_ENC_003, 'ENC-003', NULL),
        IFF(RULE_ENC_004, 'ENC-004', NULL),
        IFF(RULE_ENC_005, 'ENC-005', NULL),
        IFF(RULE_ENC_006, 'ENC-006', NULL),
        IFF(RULE_ENC_007, 'ENC-007', NULL),
        IFF(RULE_ENC_008, 'ENC-008', NULL),
        IFF(RULE_ENC_009, 'ENC-009', NULL),
        IFF(RULE_ENC_010, 'ENC-010', NULL)
    ), ', '), '') AS VALIDATION_RULE_IDS,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(RULE_ENC_001, 'Exact duplicate row within current load', NULL),
        IFF(RULE_ENC_002, 'ID is reused by conflicting records within current load', NULL),
        IFF(RULE_ENC_003, 'Encounter ID is required', NULL),
        IFF(RULE_ENC_004, 'Patient ID is required', NULL),
        IFF(RULE_ENC_005, 'Provider ID is required', NULL),
        IFF(RULE_ENC_006, 'Exact record already exists in CLEAN from an earlier load', NULL),
        IFF(RULE_ENC_007, 'ID conflicts with a CLEAN record from an earlier load', NULL),
        IFF(RULE_ENC_008, 'Start must be a valid timestamp', NULL),
        IFF(RULE_ENC_009, 'End must be a valid timestamp', NULL),
        IFF(RULE_ENC_010, 'Base encounter cost must be a representable amount', NULL)
    ), '; '), '') AS VALIDATION_MESSAGES
FROM RULE_FLAGS;
