-- Categorize prepared provider records; retain raw values and quality reasons.
-- Parameter: LOAD_RUN_ID. Use the same session as prepare_provider.sql.
-- Priority: QUARANTINED, DEDUPLICATED, WARNING, CLEAN.
-- Original source hashes detect duplicates; normalized IDs detect conflicts.
CREATE TEMPORARY TABLE CLEANSTAR.RAW.CATEGORIZED_PROVIDER AS
WITH CURRENT_LOAD AS (
    SELECT * FROM CLEANSTAR.RAW.PREPARED_PROVIDER
    WHERE LOAD_RUN_ID = %s
),
RANKED_ROWS AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY SOURCE_ROW_HASH
            ORDER BY INGESTED_AT, SOURCE_FILE, PROVIDER_ID
        ) AS DUPLICATE_NUMBER
    FROM CURRENT_LOAD
),
CURRENT_CONFLICTS AS (
    SELECT PROVIDER_ID
    FROM CURRENT_LOAD
    WHERE PROVIDER_ID IS NOT NULL
    GROUP BY PROVIDER_ID
    HAVING COUNT(DISTINCT SOURCE_ROW_HASH) > 1
),
HISTORICAL_DUPLICATES AS (
    SELECT DISTINCT source.SOURCE_ROW_HASH
    FROM CURRENT_LOAD AS source
    WHERE EXISTS (
        SELECT 1 FROM CLEANSTAR.CLEAN.PROVIDER_INFO_CLEAN AS clean
        WHERE clean.SOURCE_ROW_HASH = source.SOURCE_ROW_HASH
          AND clean.LOAD_RUN_ID <> source.LOAD_RUN_ID
    )
),
HISTORICAL_CONFLICTS AS (
    SELECT DISTINCT source.PROVIDER_ID, source.SOURCE_ROW_HASH
    FROM CURRENT_LOAD AS source
    WHERE EXISTS (
        SELECT 1 FROM CLEANSTAR.CLEAN.PROVIDER_INFO_CLEAN AS clean
        WHERE clean.PROVIDER_ID = source.PROVIDER_ID
          AND clean.SOURCE_ROW_HASH <> source.SOURCE_ROW_HASH
          AND clean.LOAD_RUN_ID <> source.LOAD_RUN_ID
    )
),
HISTORY_FLAGS AS (
    SELECT source.*,
        (conflict.PROVIDER_ID IS NOT NULL) AS CURRENT_CONFLICT,
        (duplicate.SOURCE_ROW_HASH IS NOT NULL) AS HISTORICAL_DUPLICATE,
        (history.PROVIDER_ID IS NOT NULL) AS HISTORICAL_CONFLICT
    FROM RANKED_ROWS AS source
    LEFT JOIN CURRENT_CONFLICTS AS conflict ON source.PROVIDER_ID = conflict.PROVIDER_ID
    LEFT JOIN HISTORICAL_DUPLICATES AS duplicate
        ON source.SOURCE_ROW_HASH = duplicate.SOURCE_ROW_HASH
    LEFT JOIN HISTORICAL_CONFLICTS AS history
        ON source.PROVIDER_ID = history.PROVIDER_ID
       AND source.SOURCE_ROW_HASH = history.SOURCE_ROW_HASH
),
RULE_FLAGS AS (
    SELECT *,
        IFF(DUPLICATE_NUMBER > 1, TRUE, FALSE) AS RULE_PRO_001,
        IFF(CURRENT_CONFLICT, TRUE, FALSE) AS RULE_PRO_002,
        IFF(PROVIDER_ID IS NULL, TRUE, FALSE) AS RULE_PRO_003,
        IFF(NPI IS NOT NULL AND NOT REGEXP_LIKE(NPI, '^[0-9]{10}$'), TRUE, FALSE) AS RULE_PRO_004,
        IFF(HISTORICAL_DUPLICATE, TRUE, FALSE) AS RULE_PRO_005,
        IFF(HISTORICAL_CONFLICT, TRUE, FALSE) AS RULE_PRO_006
    FROM HISTORY_FLAGS
)
SELECT *,
    CASE
        WHEN RULE_PRO_002 OR RULE_PRO_003 OR RULE_PRO_006 THEN 'QUARANTINED'
        WHEN RULE_PRO_001 OR RULE_PRO_005 THEN 'DEDUPLICATED'
        WHEN RULE_PRO_004 THEN 'WARNING'
        ELSE 'CLEAN'
    END AS VALIDATION_STATUS,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(RULE_PRO_001, 'PRO-001', NULL),
        IFF(RULE_PRO_002, 'PRO-002', NULL),
        IFF(RULE_PRO_003, 'PRO-003', NULL),
        IFF(RULE_PRO_004, 'PRO-004', NULL),
        IFF(RULE_PRO_005, 'PRO-005', NULL),
        IFF(RULE_PRO_006, 'PRO-006', NULL)
    ), ', '), '') AS VALIDATION_RULE_IDS,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(RULE_PRO_001, 'Exact duplicate row within current load', NULL),
        IFF(RULE_PRO_002, 'ID is reused by conflicting records within current load', NULL),
        IFF(RULE_PRO_003, 'Provider ID is required', NULL),
        IFF(RULE_PRO_004, 'NPI must contain exactly 10 digits', NULL),
        IFF(RULE_PRO_005, 'Exact record already exists in CLEAN from an earlier load', NULL),
        IFF(RULE_PRO_006, 'ID conflicts with a CLEAN record from an earlier load', NULL)
    ), '; '), '') AS VALIDATION_MESSAGES
FROM RULE_FLAGS;
