-- Insert original source values, including duplicate records from categorized_claims.sql.
-- Parameter: LOAD_RUN_ID.
-- Use the same Snowflake session as preparation and categorization.
-- Run both destination inserts once per load, together in a transaction.
-- These statements append rows; rerunning them would insert duplicates.
INSERT INTO CLEANSTAR.QUARANTINE.BILLING_CLAIMS_QUARANTINE (
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROVIDER_ID,
    ORGANIZATION_ID,
    PAYER_ID,
    INSURANCE_PLAN_NAME,
    MEMBER_ID,
    GROUP_NUMBER,
    RELATIONSHIP_TO_INSURED,
    PATIENT_FIRST_NAME,
    PATIENT_MIDDLE_INITIAL,
    PATIENT_LAST_NAME,
    PATIENT_SUFFIX,
    PATIENT_BIRTHDATE,
    PATIENT_GENDER,
    PATIENT_ADDRESS,
    PATIENT_CITY,
    PATIENT_STATE,
    PATIENT_ZIP,
    PATIENT_PHONE,
    SERVICE_START_DATETIME,
    SERVICE_END_DATETIME,
    ENCOUNTER_CLASS,
    PROCEDURE_CODE,
    PROCEDURE_DESCRIPTION,
    DIAGNOSIS_CODE,
    DIAGNOSIS_DESCRIPTION,
    CLAIM_AMOUNT,
    PROVIDER_NAME,
    PROVIDER_NPI,
    PROVIDER_SPECIALTY,
    CLAIM_STATUS,
    CLAIM_CREATED_DATETIME,
    VALIDATION_ERROR_COUNT,
    VALIDATION_ERRORS,
    LOAD_RUN_ID,
    SOURCE_FILE,
    INGESTED_AT,
    SOURCE_ROW_HASH,
    VALIDATION_STATUS,
    VALIDATION_RULE_IDS,
    VALIDATION_MESSAGES
)
SELECT
    categorized_claims.RAW_CLAIM_ID,
    categorized_claims.RAW_ENCOUNTER_ID,
    categorized_claims.RAW_PATIENT_ID,
    categorized_claims.RAW_PROVIDER_ID,
    categorized_claims.RAW_ORGANIZATION_ID,
    categorized_claims.RAW_PAYER_ID,
    categorized_claims.RAW_INSURANCE_PLAN_NAME,
    categorized_claims.RAW_MEMBER_ID,
    categorized_claims.RAW_GROUP_NUMBER,
    categorized_claims.RAW_RELATIONSHIP_TO_INSURED,
    categorized_claims.RAW_PATIENT_FIRST_NAME,
    categorized_claims.RAW_PATIENT_MIDDLE_INITIAL,
    categorized_claims.RAW_PATIENT_LAST_NAME,
    categorized_claims.RAW_PATIENT_SUFFIX,
    categorized_claims.RAW_PATIENT_BIRTHDATE,
    categorized_claims.RAW_PATIENT_GENDER,
    categorized_claims.RAW_PATIENT_ADDRESS,
    categorized_claims.RAW_PATIENT_CITY,
    categorized_claims.RAW_PATIENT_STATE,
    categorized_claims.RAW_PATIENT_ZIP,
    categorized_claims.RAW_PATIENT_PHONE,
    categorized_claims.RAW_SERVICE_START_DATETIME,
    categorized_claims.RAW_SERVICE_END_DATETIME,
    categorized_claims.RAW_ENCOUNTER_CLASS,
    categorized_claims.RAW_PROCEDURE_CODE,
    categorized_claims.RAW_PROCEDURE_DESCRIPTION,
    categorized_claims.RAW_DIAGNOSIS_CODE,
    categorized_claims.RAW_DIAGNOSIS_DESCRIPTION,
    categorized_claims.RAW_CLAIM_AMOUNT,
    categorized_claims.RAW_PROVIDER_NAME,
    categorized_claims.RAW_PROVIDER_NPI,
    categorized_claims.RAW_PROVIDER_SPECIALTY,
    categorized_claims.RAW_CLAIM_STATUS,
    categorized_claims.RAW_CLAIM_CREATED_DATETIME,
    categorized_claims.RAW_VALIDATION_ERROR_COUNT,
    categorized_claims.RAW_VALIDATION_ERRORS,
    categorized_claims.LOAD_RUN_ID,
    categorized_claims.SOURCE_FILE,
    categorized_claims.INGESTED_AT,
    categorized_claims.SOURCE_ROW_HASH,
    categorized_claims.VALIDATION_STATUS,
    categorized_claims.VALIDATION_RULE_IDS,
    categorized_claims.VALIDATION_MESSAGES
FROM CLEANSTAR.RAW.CATEGORIZED_CLAIMS AS categorized_claims
WHERE categorized_claims.LOAD_RUN_ID = %s
  AND categorized_claims.VALIDATION_STATUS IN ('QUARANTINED', 'DEDUPLICATED');
