-- Prepare billing claims inside Snowflake; do not change RAW or populate CLEAN yet.
-- Connector parameter: LOAD_RUN_ID.
-- Temporary tables are scoped to this pipeline session.
-- Original values are retained in RAW_* columns for later quarantine and auditing.
-- NULL/blank values normalize to NULL; supplied invalid values get failure flags.
-- Amounts use two decimal places (additional fractional digits may be rounded).
-- Error counts require integer text, preventing fractional counts from rounding.
-- Timestamp strings without offsets use the session time zone; set it deliberately
-- in the future runner. Source timestamps with Z identify UTC.
CREATE TEMPORARY TABLE CLEANSTAR.RAW.PREPARED_CLAIMS AS
WITH NORMALIZED AS (
    SELECT
        CLAIM_ID AS RAW_CLAIM_ID, ENCOUNTER_ID AS RAW_ENCOUNTER_ID, PATIENT_ID AS RAW_PATIENT_ID, PROVIDER_ID AS RAW_PROVIDER_ID, ORGANIZATION_ID AS RAW_ORGANIZATION_ID, PAYER_ID AS RAW_PAYER_ID, INSURANCE_PLAN_NAME AS RAW_INSURANCE_PLAN_NAME, MEMBER_ID AS RAW_MEMBER_ID, GROUP_NUMBER AS RAW_GROUP_NUMBER, RELATIONSHIP_TO_INSURED AS RAW_RELATIONSHIP_TO_INSURED, PATIENT_FIRST_NAME AS RAW_PATIENT_FIRST_NAME, PATIENT_MIDDLE_INITIAL AS RAW_PATIENT_MIDDLE_INITIAL, PATIENT_LAST_NAME AS RAW_PATIENT_LAST_NAME, PATIENT_SUFFIX AS RAW_PATIENT_SUFFIX, PATIENT_BIRTHDATE AS RAW_PATIENT_BIRTHDATE, PATIENT_GENDER AS RAW_PATIENT_GENDER, PATIENT_ADDRESS AS RAW_PATIENT_ADDRESS, PATIENT_CITY AS RAW_PATIENT_CITY, PATIENT_STATE AS RAW_PATIENT_STATE, PATIENT_ZIP AS RAW_PATIENT_ZIP, PATIENT_PHONE AS RAW_PATIENT_PHONE, SERVICE_START_DATETIME AS RAW_SERVICE_START_DATETIME, SERVICE_END_DATETIME AS RAW_SERVICE_END_DATETIME, ENCOUNTER_CLASS AS RAW_ENCOUNTER_CLASS, PROCEDURE_CODE AS RAW_PROCEDURE_CODE, PROCEDURE_DESCRIPTION AS RAW_PROCEDURE_DESCRIPTION, DIAGNOSIS_CODE AS RAW_DIAGNOSIS_CODE, DIAGNOSIS_DESCRIPTION AS RAW_DIAGNOSIS_DESCRIPTION, CLAIM_AMOUNT AS RAW_CLAIM_AMOUNT, PROVIDER_NAME AS RAW_PROVIDER_NAME, PROVIDER_NPI AS RAW_PROVIDER_NPI, PROVIDER_SPECIALTY AS RAW_PROVIDER_SPECIALTY, CLAIM_STATUS AS RAW_CLAIM_STATUS, CLAIM_CREATED_DATETIME AS RAW_CLAIM_CREATED_DATETIME, VALIDATION_ERROR_COUNT AS RAW_VALIDATION_ERROR_COUNT, VALIDATION_ERRORS AS RAW_VALIDATION_ERRORS,
        NULLIF(TRIM(CLAIM_ID), '') AS CLAIM_ID_TEXT,
        NULLIF(TRIM(ENCOUNTER_ID), '') AS ENCOUNTER_ID_TEXT,
        NULLIF(TRIM(PATIENT_ID), '') AS PATIENT_ID_TEXT,
        NULLIF(TRIM(PROVIDER_ID), '') AS PROVIDER_ID_TEXT,
        NULLIF(TRIM(ORGANIZATION_ID), '') AS ORGANIZATION_ID_TEXT,
        NULLIF(TRIM(PAYER_ID), '') AS PAYER_ID_TEXT,
        NULLIF(TRIM(INSURANCE_PLAN_NAME), '') AS INSURANCE_PLAN_NAME_TEXT,
        NULLIF(TRIM(MEMBER_ID), '') AS MEMBER_ID_TEXT,
        NULLIF(TRIM(GROUP_NUMBER), '') AS GROUP_NUMBER_TEXT,
        UPPER(NULLIF(TRIM(RELATIONSHIP_TO_INSURED), '')) AS RELATIONSHIP_TO_INSURED_TEXT,
        NULLIF(TRIM(PATIENT_FIRST_NAME), '') AS PATIENT_FIRST_NAME_TEXT,
        NULLIF(TRIM(PATIENT_MIDDLE_INITIAL), '') AS PATIENT_MIDDLE_INITIAL_TEXT,
        NULLIF(TRIM(PATIENT_LAST_NAME), '') AS PATIENT_LAST_NAME_TEXT,
        NULLIF(TRIM(PATIENT_SUFFIX), '') AS PATIENT_SUFFIX_TEXT,
        NULLIF(TRIM(PATIENT_BIRTHDATE), '') AS PATIENT_BIRTHDATE_TEXT,
        UPPER(NULLIF(TRIM(PATIENT_GENDER), '')) AS PATIENT_GENDER_TEXT,
        NULLIF(TRIM(PATIENT_ADDRESS), '') AS PATIENT_ADDRESS_TEXT,
        NULLIF(TRIM(PATIENT_CITY), '') AS PATIENT_CITY_TEXT,
        UPPER(NULLIF(TRIM(PATIENT_STATE), '')) AS PATIENT_STATE_TEXT,
        NULLIF(TRIM(PATIENT_ZIP), '') AS PATIENT_ZIP_TEXT,
        NULLIF(TRIM(PATIENT_PHONE), '') AS PATIENT_PHONE_TEXT,
        NULLIF(TRIM(SERVICE_START_DATETIME), '') AS SERVICE_START_DATETIME_TEXT,
        NULLIF(TRIM(SERVICE_END_DATETIME), '') AS SERVICE_END_DATETIME_TEXT,
        UPPER(NULLIF(TRIM(ENCOUNTER_CLASS), '')) AS ENCOUNTER_CLASS_TEXT,
        NULLIF(TRIM(PROCEDURE_CODE), '') AS PROCEDURE_CODE_TEXT,
        NULLIF(TRIM(PROCEDURE_DESCRIPTION), '') AS PROCEDURE_DESCRIPTION_TEXT,
        NULLIF(TRIM(DIAGNOSIS_CODE), '') AS DIAGNOSIS_CODE_TEXT,
        NULLIF(TRIM(DIAGNOSIS_DESCRIPTION), '') AS DIAGNOSIS_DESCRIPTION_TEXT,
        NULLIF(TRIM(CLAIM_AMOUNT), '') AS CLAIM_AMOUNT_TEXT,
        NULLIF(TRIM(PROVIDER_NAME), '') AS PROVIDER_NAME_TEXT,
        NULLIF(TRIM(PROVIDER_NPI), '') AS PROVIDER_NPI_TEXT,
        NULLIF(TRIM(PROVIDER_SPECIALTY), '') AS PROVIDER_SPECIALTY_TEXT,
        UPPER(NULLIF(TRIM(CLAIM_STATUS), '')) AS CLAIM_STATUS_TEXT,
        NULLIF(TRIM(CLAIM_CREATED_DATETIME), '') AS CLAIM_CREATED_DATETIME_TEXT,
        NULLIF(TRIM(VALIDATION_ERROR_COUNT), '') AS VALIDATION_ERROR_COUNT_TEXT,
        NULLIF(TRIM(VALIDATION_ERRORS), '') AS VALIDATION_ERRORS_TEXT,
        LOAD_RUN_ID,
        SOURCE_FILE,
        INGESTED_AT,
        HASH(CLAIM_ID, ENCOUNTER_ID, PATIENT_ID, PROVIDER_ID, ORGANIZATION_ID, PAYER_ID, INSURANCE_PLAN_NAME, MEMBER_ID, GROUP_NUMBER, RELATIONSHIP_TO_INSURED, PATIENT_FIRST_NAME, PATIENT_MIDDLE_INITIAL, PATIENT_LAST_NAME, PATIENT_SUFFIX, PATIENT_BIRTHDATE, PATIENT_GENDER, PATIENT_ADDRESS, PATIENT_CITY, PATIENT_STATE, PATIENT_ZIP, PATIENT_PHONE, SERVICE_START_DATETIME, SERVICE_END_DATETIME, ENCOUNTER_CLASS, PROCEDURE_CODE, PROCEDURE_DESCRIPTION, DIAGNOSIS_CODE, DIAGNOSIS_DESCRIPTION, CLAIM_AMOUNT, PROVIDER_NAME, PROVIDER_NPI, PROVIDER_SPECIALTY, CLAIM_STATUS, CLAIM_CREATED_DATETIME, VALIDATION_ERROR_COUNT, VALIDATION_ERRORS) AS SOURCE_ROW_HASH
    FROM CLEANSTAR.RAW.BILLING_CLAIMS_RAW
    WHERE LOAD_RUN_ID = %s
),
CONVERTED AS (
    SELECT
        NORMALIZED.*, CLAIM_ID_TEXT AS CLAIM_ID, ENCOUNTER_ID_TEXT AS ENCOUNTER_ID, PATIENT_ID_TEXT AS PATIENT_ID, PROVIDER_ID_TEXT AS PROVIDER_ID, ORGANIZATION_ID_TEXT AS ORGANIZATION_ID, PAYER_ID_TEXT AS PAYER_ID, INSURANCE_PLAN_NAME_TEXT AS INSURANCE_PLAN_NAME, MEMBER_ID_TEXT AS MEMBER_ID, GROUP_NUMBER_TEXT AS GROUP_NUMBER, RELATIONSHIP_TO_INSURED_TEXT AS RELATIONSHIP_TO_INSURED, PATIENT_FIRST_NAME_TEXT AS PATIENT_FIRST_NAME, PATIENT_MIDDLE_INITIAL_TEXT AS PATIENT_MIDDLE_INITIAL, PATIENT_LAST_NAME_TEXT AS PATIENT_LAST_NAME, PATIENT_SUFFIX_TEXT AS PATIENT_SUFFIX, TRY_TO_DATE(PATIENT_BIRTHDATE_TEXT, 'YYYY-MM-DD') AS PATIENT_BIRTHDATE, PATIENT_GENDER_TEXT AS PATIENT_GENDER, PATIENT_ADDRESS_TEXT AS PATIENT_ADDRESS, PATIENT_CITY_TEXT AS PATIENT_CITY, PATIENT_STATE_TEXT AS PATIENT_STATE, PATIENT_ZIP_TEXT AS PATIENT_ZIP, PATIENT_PHONE_TEXT AS PATIENT_PHONE,
        TRY_TO_TIMESTAMP_TZ(SERVICE_START_DATETIME_TEXT, 'AUTO') AS SERVICE_START_DATETIME,
        TRY_TO_TIMESTAMP_TZ(SERVICE_END_DATETIME_TEXT, 'AUTO') AS SERVICE_END_DATETIME,
        ENCOUNTER_CLASS_TEXT AS ENCOUNTER_CLASS,
        PROCEDURE_CODE_TEXT AS PROCEDURE_CODE,
        PROCEDURE_DESCRIPTION_TEXT AS PROCEDURE_DESCRIPTION,
        DIAGNOSIS_CODE_TEXT AS DIAGNOSIS_CODE,
        DIAGNOSIS_DESCRIPTION_TEXT AS DIAGNOSIS_DESCRIPTION,
        TRY_TO_DECIMAL(CLAIM_AMOUNT_TEXT, 18, 2) AS CLAIM_AMOUNT,
        PROVIDER_NAME_TEXT AS PROVIDER_NAME,
        PROVIDER_NPI_TEXT AS PROVIDER_NPI,
        PROVIDER_SPECIALTY_TEXT AS PROVIDER_SPECIALTY,
        CLAIM_STATUS_TEXT AS CLAIM_STATUS,
        TRY_TO_TIMESTAMP_TZ(CLAIM_CREATED_DATETIME_TEXT, 'AUTO') AS CLAIM_CREATED_DATETIME,
        CASE WHEN REGEXP_LIKE(VALIDATION_ERROR_COUNT_TEXT, '^[+-]?[0-9]+$') THEN TRY_TO_NUMBER(VALIDATION_ERROR_COUNT_TEXT, 38, 0) END AS VALIDATION_ERROR_COUNT,
        VALIDATION_ERRORS_TEXT AS VALIDATION_ERRORS
    FROM NORMALIZED
)
SELECT
    RAW_CLAIM_ID, RAW_ENCOUNTER_ID, RAW_PATIENT_ID, RAW_PROVIDER_ID, RAW_ORGANIZATION_ID, RAW_PAYER_ID, RAW_INSURANCE_PLAN_NAME, RAW_MEMBER_ID, RAW_GROUP_NUMBER, RAW_RELATIONSHIP_TO_INSURED, RAW_PATIENT_FIRST_NAME, RAW_PATIENT_MIDDLE_INITIAL, RAW_PATIENT_LAST_NAME, RAW_PATIENT_SUFFIX, RAW_PATIENT_BIRTHDATE, RAW_PATIENT_GENDER, RAW_PATIENT_ADDRESS, RAW_PATIENT_CITY, RAW_PATIENT_STATE, RAW_PATIENT_ZIP, RAW_PATIENT_PHONE, RAW_SERVICE_START_DATETIME, RAW_SERVICE_END_DATETIME, RAW_ENCOUNTER_CLASS, RAW_PROCEDURE_CODE, RAW_PROCEDURE_DESCRIPTION, RAW_DIAGNOSIS_CODE, RAW_DIAGNOSIS_DESCRIPTION, RAW_CLAIM_AMOUNT, RAW_PROVIDER_NAME, RAW_PROVIDER_NPI, RAW_PROVIDER_SPECIALTY, RAW_CLAIM_STATUS, RAW_CLAIM_CREATED_DATETIME, RAW_VALIDATION_ERROR_COUNT, RAW_VALIDATION_ERRORS, CLAIM_ID, ENCOUNTER_ID, PATIENT_ID, PROVIDER_ID, ORGANIZATION_ID, PAYER_ID, INSURANCE_PLAN_NAME, MEMBER_ID, GROUP_NUMBER, RELATIONSHIP_TO_INSURED, PATIENT_FIRST_NAME, PATIENT_MIDDLE_INITIAL, PATIENT_LAST_NAME, PATIENT_SUFFIX, PATIENT_BIRTHDATE, PATIENT_GENDER, PATIENT_ADDRESS, PATIENT_CITY, PATIENT_STATE, PATIENT_ZIP, PATIENT_PHONE, SERVICE_START_DATETIME, SERVICE_END_DATETIME, ENCOUNTER_CLASS, PROCEDURE_CODE, PROCEDURE_DESCRIPTION, DIAGNOSIS_CODE, DIAGNOSIS_DESCRIPTION, CLAIM_AMOUNT, PROVIDER_NAME, PROVIDER_NPI, PROVIDER_SPECIALTY, CLAIM_STATUS, CLAIM_CREATED_DATETIME, VALIDATION_ERROR_COUNT, VALIDATION_ERRORS, LOAD_RUN_ID, SOURCE_FILE, INGESTED_AT, SOURCE_ROW_HASH,
    (PATIENT_BIRTHDATE_TEXT IS NOT NULL AND PATIENT_BIRTHDATE IS NULL) AS PATIENT_BIRTHDATE_CONVERSION_FAILED,
    (SERVICE_START_DATETIME_TEXT IS NOT NULL AND SERVICE_START_DATETIME IS NULL) AS SERVICE_START_DATETIME_CONVERSION_FAILED,
    (SERVICE_END_DATETIME_TEXT IS NOT NULL AND SERVICE_END_DATETIME IS NULL) AS SERVICE_END_DATETIME_CONVERSION_FAILED,
    (CLAIM_CREATED_DATETIME_TEXT IS NOT NULL AND CLAIM_CREATED_DATETIME IS NULL) AS CLAIM_CREATED_DATETIME_CONVERSION_FAILED,
    (CLAIM_AMOUNT_TEXT IS NOT NULL AND CLAIM_AMOUNT IS NULL) AS CLAIM_AMOUNT_CONVERSION_FAILED,
    (VALIDATION_ERROR_COUNT_TEXT IS NOT NULL AND VALIDATION_ERROR_COUNT IS NULL) AS VALIDATION_ERROR_COUNT_CONVERSION_FAILED
FROM CONVERTED;
