-- Prepare encounter records for the current load; preserve original RAW_* values.
-- Parameter: LOAD_RUN_ID. Run once in the pipeline session before categorization.
-- Blank optional values become NULL; supplied invalid typed values are flagged.
-- Amounts round to two decimal places. Timestamps without offsets use the session time zone.
-- The future runner must set the session time zone deliberately.
CREATE TEMPORARY TABLE CLEANSTAR.RAW.PREPARED_ENCOUNTER AS
WITH NORMALIZED AS (
    SELECT
        ENCOUNTER_ID AS RAW_ENCOUNTER_ID,
        START_DATETIME AS RAW_START_DATETIME,
        END_DATETIME AS RAW_END_DATETIME,
        PATIENT_ID AS RAW_PATIENT_ID,
        ORGANIZATION_ID AS RAW_ORGANIZATION_ID,
        PROVIDER_ID AS RAW_PROVIDER_ID,
        ENCOUNTER_CLASS AS RAW_ENCOUNTER_CLASS,
        ENCOUNTER_CODE AS RAW_ENCOUNTER_CODE,
        ENCOUNTER_DESCRIPTION AS RAW_ENCOUNTER_DESCRIPTION,
        DIAGNOSIS_CODE AS RAW_DIAGNOSIS_CODE,
        DIAGNOSIS_DESCRIPTION AS RAW_DIAGNOSIS_DESCRIPTION,
        BASE_ENCOUNTER_COST AS RAW_BASE_ENCOUNTER_COST,
        NULLIF(TRIM(ENCOUNTER_ID), '') AS ENCOUNTER_ID_TEXT,
        NULLIF(TRIM(START_DATETIME), '') AS START_DATETIME_TEXT,
        NULLIF(TRIM(END_DATETIME), '') AS END_DATETIME_TEXT,
        NULLIF(TRIM(PATIENT_ID), '') AS PATIENT_ID_TEXT,
        NULLIF(TRIM(ORGANIZATION_ID), '') AS ORGANIZATION_ID_TEXT,
        NULLIF(TRIM(PROVIDER_ID), '') AS PROVIDER_ID_TEXT,
        UPPER(NULLIF(TRIM(ENCOUNTER_CLASS), '')) AS ENCOUNTER_CLASS_TEXT,
        NULLIF(TRIM(ENCOUNTER_CODE), '') AS ENCOUNTER_CODE_TEXT,
        NULLIF(TRIM(ENCOUNTER_DESCRIPTION), '') AS ENCOUNTER_DESCRIPTION_TEXT,
        NULLIF(TRIM(DIAGNOSIS_CODE), '') AS DIAGNOSIS_CODE_TEXT,
        NULLIF(TRIM(DIAGNOSIS_DESCRIPTION), '') AS DIAGNOSIS_DESCRIPTION_TEXT,
        NULLIF(TRIM(BASE_ENCOUNTER_COST), '') AS BASE_ENCOUNTER_COST_TEXT,
        LOAD_RUN_ID,
        SOURCE_FILE,
        INGESTED_AT,
        HASH(ENCOUNTER_ID, START_DATETIME, END_DATETIME, PATIENT_ID, ORGANIZATION_ID, PROVIDER_ID, ENCOUNTER_CLASS, ENCOUNTER_CODE, ENCOUNTER_DESCRIPTION, DIAGNOSIS_CODE, DIAGNOSIS_DESCRIPTION, BASE_ENCOUNTER_COST) AS SOURCE_ROW_HASH
    FROM CLEANSTAR.RAW.ENCOUNTER_INFO_RAW
    WHERE LOAD_RUN_ID = %s
),
CONVERTED AS (
    SELECT
        NORMALIZED.*,
        ENCOUNTER_ID_TEXT AS ENCOUNTER_ID,
        TRY_TO_TIMESTAMP_TZ(START_DATETIME_TEXT, 'AUTO') AS START_DATETIME,
        TRY_TO_TIMESTAMP_TZ(END_DATETIME_TEXT, 'AUTO') AS END_DATETIME,
        PATIENT_ID_TEXT AS PATIENT_ID,
        ORGANIZATION_ID_TEXT AS ORGANIZATION_ID,
        PROVIDER_ID_TEXT AS PROVIDER_ID,
        ENCOUNTER_CLASS_TEXT AS ENCOUNTER_CLASS,
        ENCOUNTER_CODE_TEXT AS ENCOUNTER_CODE,
        ENCOUNTER_DESCRIPTION_TEXT AS ENCOUNTER_DESCRIPTION,
        DIAGNOSIS_CODE_TEXT AS DIAGNOSIS_CODE,
        DIAGNOSIS_DESCRIPTION_TEXT AS DIAGNOSIS_DESCRIPTION,
        TRY_TO_DECIMAL(BASE_ENCOUNTER_COST_TEXT, 18, 2) AS BASE_ENCOUNTER_COST
    FROM NORMALIZED
)
SELECT
    RAW_ENCOUNTER_ID,
    RAW_START_DATETIME,
    RAW_END_DATETIME,
    RAW_PATIENT_ID,
    RAW_ORGANIZATION_ID,
    RAW_PROVIDER_ID,
    RAW_ENCOUNTER_CLASS,
    RAW_ENCOUNTER_CODE,
    RAW_ENCOUNTER_DESCRIPTION,
    RAW_DIAGNOSIS_CODE,
    RAW_DIAGNOSIS_DESCRIPTION,
    RAW_BASE_ENCOUNTER_COST,
    ENCOUNTER_ID,
    START_DATETIME,
    END_DATETIME,
    PATIENT_ID,
    ORGANIZATION_ID,
    PROVIDER_ID,
    ENCOUNTER_CLASS,
    ENCOUNTER_CODE,
    ENCOUNTER_DESCRIPTION,
    DIAGNOSIS_CODE,
    DIAGNOSIS_DESCRIPTION,
    BASE_ENCOUNTER_COST,
    LOAD_RUN_ID,
    SOURCE_FILE,
    INGESTED_AT,
    SOURCE_ROW_HASH,
    (START_DATETIME_TEXT IS NOT NULL AND START_DATETIME IS NULL) AS START_DATETIME_CONVERSION_FAILED,
    (END_DATETIME_TEXT IS NOT NULL AND END_DATETIME IS NULL) AS END_DATETIME_CONVERSION_FAILED,
    (BASE_ENCOUNTER_COST_TEXT IS NOT NULL AND BASE_ENCOUNTER_COST IS NULL) AS BASE_ENCOUNTER_COST_CONVERSION_FAILED
FROM CONVERTED;
