-- Prepare provider records for the current load; preserve original RAW_* values.
-- Parameter: LOAD_RUN_ID. Run once in the pipeline session before categorization.
-- Blank optional values become NULL; supplied invalid typed values are flagged.
CREATE TEMPORARY TABLE CLEANSTAR.RAW.PREPARED_PROVIDER AS
WITH NORMALIZED AS (
    SELECT
        PROVIDER_ID AS RAW_PROVIDER_ID,
        ORGANIZATION_ID AS RAW_ORGANIZATION_ID,
        PROVIDER_NAME AS RAW_PROVIDER_NAME,
        SPECIALTY AS RAW_SPECIALTY,
        NPI AS RAW_NPI,
        NULLIF(TRIM(PROVIDER_ID), '') AS PROVIDER_ID_TEXT,
        NULLIF(TRIM(ORGANIZATION_ID), '') AS ORGANIZATION_ID_TEXT,
        NULLIF(TRIM(PROVIDER_NAME), '') AS PROVIDER_NAME_TEXT,
        NULLIF(TRIM(SPECIALTY), '') AS SPECIALTY_TEXT,
        NULLIF(TRIM(NPI), '') AS NPI_TEXT,
        LOAD_RUN_ID,
        SOURCE_FILE,
        INGESTED_AT,
        HASH(PROVIDER_ID, ORGANIZATION_ID, PROVIDER_NAME, SPECIALTY, NPI) AS SOURCE_ROW_HASH
    FROM CLEANSTAR.RAW.PROVIDER_INFO_RAW
    WHERE LOAD_RUN_ID = %s
),
CONVERTED AS (
    SELECT
        NORMALIZED.*,
        PROVIDER_ID_TEXT AS PROVIDER_ID,
        ORGANIZATION_ID_TEXT AS ORGANIZATION_ID,
        PROVIDER_NAME_TEXT AS PROVIDER_NAME,
        SPECIALTY_TEXT AS SPECIALTY,
        NPI_TEXT AS NPI
    FROM NORMALIZED
)
SELECT
    RAW_PROVIDER_ID,
    RAW_ORGANIZATION_ID,
    RAW_PROVIDER_NAME,
    RAW_SPECIALTY,
    RAW_NPI,
    PROVIDER_ID,
    ORGANIZATION_ID,
    PROVIDER_NAME,
    SPECIALTY,
    NPI,
    LOAD_RUN_ID,
    SOURCE_FILE,
    INGESTED_AT,
    SOURCE_ROW_HASH
FROM CONVERTED;
