-- Manual test reset: removes every row from all 12 CleanStar pipeline tables.
-- Keep table definitions, grants, staged files, local CSVs, and saved reports.
-- TRUNCATE also clears table load metadata so the same files can be loaded again.
-- Run separately from the pipeline, when no pipeline run is active.
USE ROLE SYSADMIN;

TRUNCATE TABLE CLEANSTAR.RAW.BILLING_CLAIMS_RAW;
TRUNCATE TABLE CLEANSTAR.RAW.ENCOUNTER_INFO_RAW;
TRUNCATE TABLE CLEANSTAR.RAW.PATIENT_INFO_RAW;
TRUNCATE TABLE CLEANSTAR.RAW.PROVIDER_INFO_RAW;

TRUNCATE TABLE CLEANSTAR.CLEAN.BILLING_CLAIMS_CLEAN;
TRUNCATE TABLE CLEANSTAR.CLEAN.ENCOUNTER_INFO_CLEAN;
TRUNCATE TABLE CLEANSTAR.CLEAN.PATIENT_INFO_CLEAN;
TRUNCATE TABLE CLEANSTAR.CLEAN.PROVIDER_INFO_CLEAN;

TRUNCATE TABLE CLEANSTAR.QUARANTINE.BILLING_CLAIMS_QUARANTINE;
TRUNCATE TABLE CLEANSTAR.QUARANTINE.ENCOUNTER_INFO_QUARANTINE;
TRUNCATE TABLE CLEANSTAR.QUARANTINE.PATIENT_INFO_QUARANTINE;
TRUNCATE TABLE CLEANSTAR.QUARANTINE.PROVIDER_INFO_QUARANTINE;
