-- Run after roles.sql and all infrastructure and table creation scripts.
USE ROLE SECURITYADMIN;

-- Access the compute and the containers holding project objects.
GRANT USAGE ON WAREHOUSE CLEANSTAR_WH TO ROLE CLEANSTAR_ROLE;
GRANT USAGE ON DATABASE CLEANSTAR TO ROLE CLEANSTAR_ROLE;
GRANT USAGE ON SCHEMA CLEANSTAR.RAW TO ROLE CLEANSTAR_ROLE;
GRANT USAGE ON SCHEMA CLEANSTAR.CLEAN TO ROLE CLEANSTAR_ROLE;
GRANT USAGE ON SCHEMA CLEANSTAR.QUARANTINE TO ROLE CLEANSTAR_ROLE;

-- Parse, upload, and read source files. Internal stages use READ and WRITE.
GRANT USAGE ON FILE FORMAT CLEANSTAR.RAW.CSV_FORMAT TO ROLE CLEANSTAR_ROLE;
GRANT READ ON STAGE CLEANSTAR.RAW.RAW_STAGE TO ROLE CLEANSTAR_ROLE;
GRANT WRITE ON STAGE CLEANSTAR.RAW.RAW_STAGE TO ROLE CLEANSTAR_ROLE;

-- Read data and insert new rows into the existing pipeline tables.
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CLEANSTAR.RAW TO ROLE CLEANSTAR_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CLEANSTAR.CLEAN TO ROLE CLEANSTAR_ROLE;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CLEANSTAR.QUARANTINE TO ROLE CLEANSTAR_ROLE;

-- Apply the same access to tables added later in these schemas.
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA CLEANSTAR.RAW TO ROLE CLEANSTAR_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA CLEANSTAR.CLEAN TO ROLE CLEANSTAR_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA CLEANSTAR.QUARANTINE TO ROLE CLEANSTAR_ROLE;

-- Finish setup using the pipeline role.
USE ROLE CLEANSTAR_ROLE;
